site_name: NW.js Documentation
theme: readthedocs
theme_dir: 'custom_theme'
# theme:
#     name: readthedocs
#     custom_dir: custom_theme
markdown_extensions:
    - markdown.extensions.toc
    - markdown.extensions.admonition
    - markdown.extensions.smarty
    - markdown.extensions.nl2br
    - markdown.extensions.codehilite:
        guess_lang: false
    - pymdownx.extra
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.tilde
    - pymdownx.caret
    - pymdownx.smartsymbols
    - pymdownx.tasklist
    - pymdownx.progressbar
    - pymdownx.arithmatex
    - pymdownx.mark
    - pymdownx.critic
pages:
# nav:
    - '主页': 'index.md'
    - '应用开发':
        - '开始': 'For Users/Getting Started.md'
        - '开发者工具与调试': 'For Users/Debugging with DevTools.md'
        - '打包与发布': 'For Users/Package and Distribute.md'
        - '常见问题': 'For Users/FAQ.md'
        - '版本升级':
            - '从 0.12 升级到 0.13': 'For Users/Migration/From 0.12 to 0.13.md'
        - '进阶':
            - '构建风格': 'For Users/Advanced/Build Flavors.md'
            - '内容验证': 'For Users/Advanced/Content Verification.md'
            - '自定义菜单栏': 'For Users/Advanced/Customize Menubar.md'
            - 'JavaScript 环境': 'For Users/Advanced/JavaScript Contexts in NW.js.md'
            - '保护 JavaScript 源代码': 'For Users/Advanced/Protect JavaScript Source Code.md'
            - '安全性': 'For Users/Advanced/Security in NW.js.md'
            - 'Mac 应用商店支持': 'For Users/Advanced/Support for Mac App Store.md'
            - 'ChromeDriver 自动化测试': 'For Users/Advanced/Test with ChromeDriver.md'
            - '透明窗口': 'For Users/Advanced/Transparent Window.md'
            - 'Flash 插件': 'For Users/Advanced/Use Flash Plugin.md'
            - 'NaCl': 'For Users/Advanced/Use NaCl in NW.js.md'
            - 'Node 原生模块': 'For Users/Advanced/Use Native Node Modules.md'
            - '自更新': 'For Users/Advanced/Autoupdates.md'
    - 'API':
        - 'App（应用）': 'References/App.md'
        - 'DOM 的改动': 'References/Changes to DOM.md'
        - 'Node 的改动': 'References/Changes to Node.md'
        - 'Clipboard（剪贴板）': 'References/Clipboard.md'
        - '命令行参数': 'References/Command Line Options.md'
        - 'Chrome 扩展 API': 'References/Chrome Extension APIs.md'
        - '配置格式': 'References/Manifest Format.md'
        - 'Menu（菜单）': 'References/Menu.md'
        - 'MenuItem（菜单项）': 'References/MenuItem.md'
        - 'Screen（屏幕）': 'References/Screen.md'
        - 'Shell（桌面操作）': 'References/Shell.md'
        - 'Shortcut（快捷键）': 'References/Shortcut.md'
        - 'Tray（托盘图标）': 'References/Tray.md'
        - 'webview 标签': 'References/webview Tag.md'
        - 'Window（窗口）': 'References/Window.md'
    - '项目开发':
        - '构建 NW.js': 'For Developers/Building NW.js.md'
        - '贡献代码': 'For Developers/Contributing to NW.js.md'
        - '私有编解码器': 'For Developers/Enable Proprietary Codecs.md'
        - '相关仓库': 'For Developers/Repositories.md'
        - '了解崩溃机制': 'For Developers/Understanding Crash Dump.md'
        - '编写文档': 'For Developers/Writing Documents for NW.js.md'
        - '编写测试用例': 'For Developers/Writing Test Cases for NW.js.md'
        - '文档贡献者': 'For Developers/Contributors of Documents.md'
